// lib/bibleBooks.ts

// Mapping of book names to abbreviations
export const bookNameToAbbrevMap: Record<string, string> = {
    "Genesis": "gn",
    "Exodus": "ex",
    "Leviticus": "lv",
    "Numbers": "nm",
    "Deuteronomy": "dt",
    "Joshua": "js",
    "Judges": "jud",
    "Ruth": "rt",
    "1 Samuel": "1sm",
    "2 Samuel": "2sm",
    "1 Kings": "1kgs",
    "2 Kings": "2kgs",
    "1 Chronicles": "1ch",
    "2 Chronicles": "2ch",
    "Ezra": "ezr",
    "Nehemiah": "ne",
    "Esther": "et",
    "Job": "job",
    "Psalms": "ps",
    "Proverbs": "prv",
    "Ecclesiastes": "ec",
    "Song of Solomon": "so",
    "Isaiah": "is",
    "Jeremiah": "jr",
    "Lamentations": "lm",
    "Ezekiel": "ez",
    "Daniel": "dn",
    "Hosea": "ho",
    "Joel": "jl",
    "Amos": "am",
    "Obadiah": "ob",
    "Jonah": "jn",
    "Micah": "mi",
    "Nahum": "na",
    "Habakkuk": "hk",
    "Zephaniah": "zp",
    "Haggai": "hg",
    "Zechariah": "zc",
    "Malachi": "ml",
    "Matthew": "mt",
    "Mark": "mk",
    "Luke": "lk",
    "John": "jo",
    "Acts": "act",
    "Romans": "rm",
    "1 Corinthians": "1co",
    "2 Corinthians": "2co",
    "Galatians": "gl",
    "Ephesians": "eph",
    "Philippians": "ph",
    "Colossians": "cl",
    "1 Thessalonians": "1ts",
    "2 Thessalonians": "2ts",
    "1 Timothy": "1tm",
    "2 Timothy": "2tm",
    "Titus": "tt",
    "Philemon": "phm",
    "Hebrews": "hb",
    "James": "jm",
    "1 Peter": "1pe",
    "2 Peter": "2pe",
    "1 John": "1jo",
    "2 John": "2jo",
    "3 John": "3jo",
    "Jude": "jd",
    "Revelation": "re"
  };
  
  // List of books and their chapter counts
  export const books = [
    { name: "Genesis", abbrev: "gn", chapters: 50 },
    { name: "Exodus", abbrev: "ex", chapters: 40 },
    { name: "Leviticus", abbrev: "lv", chapters: 27 },
    { name: "Numbers", abbrev: "nm", chapters: 36 },
    { name: "Deuteronomy", abbrev: "dt", chapters: 34 },
    { name: "Joshua", abbrev: "js", chapters: 24 },
    { name: "Judges", abbrev: "jud", chapters: 21 },
    { name: "Ruth", abbrev: "rt", chapters: 4 },
    { name: "1 Samuel", abbrev: "1sm", chapters: 31 },
    { name: "2 Samuel", abbrev: "2sm", chapters: 24 },
    { name: "1 Kings", abbrev: "1kgs", chapters: 22 },
    { name: "2 Kings", abbrev: "2kgs", chapters: 25 },
    { name: "1 Chronicles", abbrev: "1ch", chapters: 29 },
    { name: "2 Chronicles", abbrev: "2ch", chapters: 36 },
    { name: "Ezra", abbrev: "ezr", chapters: 10 },
    { name: "Nehemiah", abbrev: "ne", chapters: 13 },
    { name: "Esther", abbrev: "et", chapters: 10 },
    { name: "Job", abbrev: "job", chapters: 42 },
    { name: "Psalms", abbrev: "ps", chapters: 150 },
    { name: "Proverbs", abbrev: "prv", chapters: 31 },
    { name: "Ecclesiastes", abbrev: "ec", chapters: 12 },
    { name: "Song of Solomon", abbrev: "so", chapters: 8 },
    { name: "Isaiah", abbrev: "is", chapters: 66 },
    { name: "Jeremiah", abbrev: "jr", chapters: 52 },
    { name: "Lamentations", abbrev: "lm", chapters: 5 },
    { name: "Ezekiel", abbrev: "ez", chapters: 48 },
    { name: "Daniel", abbrev: "dn", chapters: 12 },
    { name: "Hosea", abbrev: "ho", chapters: 14 },
    { name: "Joel", abbrev: "jl", chapters: 3 },
    { name: "Amos", abbrev: "am", chapters: 9 },
    { name: "Obadiah", abbrev: "ob", chapters: 1 },
    { name: "Jonah", abbrev: "jn", chapters: 4 },
    { name: "Micah", abbrev: "mi", chapters: 7 },
    { name: "Nahum", abbrev: "na", chapters: 3 },
    { name: "Habakkuk", abbrev: "hk", chapters: 3 },
    { name: "Zephaniah", abbrev: "zp", chapters: 3 },
    { name: "Haggai", abbrev: "hg", chapters: 2 },
    { name: "Zechariah", abbrev: "zc", chapters: 14 },
    { name: "Malachi", abbrev: "ml", chapters: 4 },
    { name: "Matthew", abbrev: "mt", chapters: 28 },
    { name: "Mark", abbrev: "mk", chapters: 16 },
    { name: "Luke", abbrev: "lk", chapters: 24 },
    { name: "John", abbrev: "jo", chapters: 21 },
    { name: "Acts", abbrev: "act", chapters: 28 },
    { name: "Romans", abbrev: "rm", chapters: 16 },
    { name: "1 Corinthians", abbrev: "1co", chapters: 16 },
    { name: "2 Corinthians", abbrev: "2co", chapters: 13 },
    { name: "Galatians", abbrev: "gl", chapters: 6 },
    { name: "Ephesians", abbrev: "eph", chapters: 6 },
    { name: "Philippians", abbrev: "ph", chapters: 4 },
    { name: "Colossians", abbrev: "cl", chapters: 4 },
    { name: "1 Thessalonians", abbrev: "1ts", chapters: 5 },
    { name: "2 Thessalonians", abbrev: "2ts", chapters: 3 },
    { name: "1 Timothy", abbrev: "1tm", chapters: 6 },
    { name: "2 Timothy", abbrev: "2tm", chapters: 4 },
    { name: "Titus", abbrev: "tt", chapters: 3 },
    { name: "Philemon", abbrev: "phm", chapters: 1 },
    { name: "Hebrews", abbrev: "hb", chapters: 13 },
    { name: "James", abbrev: "jm", chapters: 5 },
    { name: "1 Peter", abbrev: "1pe", chapters: 5 },
    { name: "2 Peter", abbrev: "2pe", chapters: 3 },
    { name: "1 John", abbrev: "1jo", chapters: 5 },
    { name: "2 John", abbrev: "2jo", chapters: 1 },
    { name: "3 John", abbrev: "3jo", chapters: 1 },
    { name: "Jude", abbrev: "jd", chapters: 1 },
    { name: "Revelation", abbrev: "re", chapters: 22 },
  ];
  